services:
  apache:
    image: asadkrmv/trainee-apache

  nginx:
    image: asadkrmv/jenkins-nginx
    volumes:
      - nginx-logs:/var/log/nginx/
    ports:
      - 80:8090
    depends_on:
      - apache
    
  logs:
    image: asadkrmv/jenkins-logs
    volumes:
      - nginx-logs:/var/log/nginx/
    depends_on:
      - nginx
    command: sh -c "python /var/scripts/logs.py"

volumes:
  nginx-logs: